"""`forge docs` — generate documentation, two kinds for two audiences.

`framework` documents the tool: architecture, concepts, command reference,
lifecycle. The command reference and the lifecycle table are generated from
argparse and from lifecycle.py rather than written by hand, because hand-written
command docs are wrong within a week and nobody notices until someone follows
them.

`catalog` documents a label: a browsable release catalogue, per act, with
artwork, lyrics, matrix, measured stats and links. Generated from the ledger, so
it cannot disagree with the data it describes.

On the wiki question: a GitHub wiki is a separate git repo, which means a second
push target and something to keep in sync — and it would drift the first time
anyone forgot. Committed docs also get working relative paths to artwork that is
already in the tree, and they are reviewable in the same change that caused them.
`--out` exists so a wiki clone can still be the destination if browser editing
matters more than any of that.

Markdown is the primary output because GitHub renders it natively. HTML is
optional and exists for one reason: GitHub strips `<audio>` from markdown, so a
playable catalogue has to be HTML. Since the masters live in the repo, that
player needs no third party and no hosting plan — it works from a local file.
"""

from __future__ import annotations

import html
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import config as config_mod
from . import context as context_mod
from . import ledger as ledger_mod
from . import lifecycle as lc_mod
from . import variety as variety_mod
from .config import Config

DOCS = config_mod.REPO_ROOT / "docs"


@dataclass
class DocFile:
    path: str
    content: str


@dataclass
class DocSet:
    kind: str
    files: list[DocFile] = field(default_factory=list)

    def write(self, root: Path) -> dict[str, Any]:
        for f in self.files:
            dest = root / f.path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(f.content, encoding="utf-8")
        return {
            "kind": self.kind,
            "root": str(root),
            "files": [f.path for f in self.files],
            "count": len(self.files),
        }


# ---------------------------------------------------------------------------
# framework docs
# ---------------------------------------------------------------------------
def _command_reference() -> str:
    """Generated by walking the real parser. A hand-written command reference is
    wrong within a week and nobody notices until someone follows it."""
    from .cli import build_parser

    parser = build_parser()
    subs = [
        a for a in parser._actions
        if a.__class__.__name__ == "_SubParsersAction"
    ]
    lines = [
        "# Command reference",
        "",
        "Generated from the argument parser — this file cannot drift from the code.",
        "",
        "```bash",
        "python3 -m framework.forge <command> [options]",
        "```",
        "",
        "Commands that report accept `--json`. Structured output is the primary",
        "rendering, since the tool is normally driven by an agent; the formatted",
        "view is a second rendering of the same data.",
        "",
    ]
    if not subs:
        return "\n".join(lines)

    for name, sub in sorted(subs[0].choices.items()):
        lines.append(f"## `{name}`")
        lines.append("")
        if sub.description or sub.prog:
            help_text = subs[0]._choices_actions
            match = next((c for c in help_text if c.dest == name), None)
            if match and match.help:
                lines.append(match.help)
                lines.append("")
        opts = []
        for act in sub._actions:
            if act.dest in ("help",):
                continue
            flags = ", ".join(f"`{o}`" for o in act.option_strings) or f"`{act.dest}`"
            choices = f" — one of {', '.join(map(str, act.choices))}" if act.choices else ""
            required = " **(required)**" if getattr(act, "required", False) else ""
            opts.append(f"| {flags} | {act.help or ''}{choices}{required} |")
        if opts:
            lines.append("| Option | Meaning |")
            lines.append("| --- | --- |")
            lines.extend(opts)
            lines.append("")
    return "\n".join(lines)


def _lifecycle_doc() -> str:
    lines = [
        "# The song lifecycle",
        "",
        "Generated from `lifecycle.py`.",
        "",
        "A song is tracked from raw input to adjudicated glitch log. **Stage is",
        "derived from what exists on disk**, never read from a field somebody has",
        "to remember to update — a recorded stage that disagrees with reality is",
        "worse than no stage at all.",
        "",
        "`imported` sits outside the sequence. Legacy tracks enter there rather",
        "than at `mastered`, because they genuinely did not go through this",
        "pipeline and inventing a spark for them would fabricate provenance.",
        "",
        "| # | Stage | Gate | Requires | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in lc_mod.STAGES:
        order = "—" if s.order < 0 else str(s.order)
        req = ", ".join(f"`{r}`" for r in s.requires) or "—"
        lines.append(f"| {order} | `{s.id}` | {s.gate} | {req} | {s.summary} |")

    lines += ["", "## What each human gate asks for", ""]
    for s in lc_mod.STAGES:
        if s.gate == lc_mod.HUMAN and s.asks:
            lines += [f"### `{s.id}`", "", s.asks, ""]
    return "\n".join(lines)


ARCHITECTURE = """\
# Architecture

## Two layers

```
framework/     generic — lift this into any label project untouched
  forge/         the Python toolchain
  prompts/       the prompt library, as data
  stances.yaml   the rhetorical stance taxonomy
label/         one label's instance
  label.yaml     roster, asset roots, eras, canonical phrases
  substrate.md   the shared biography the acts draw on
  bands/<slug>/  band.yaml, dossier.md, retired.yaml, tracks.yaml, lyrics/
  audio/         masters, committed
  artwork/       covers, committed
  sparks/        raw human input — gitignored
  briefs/        derived briefs — committed
```

The split is what makes the repo usable as a template: `framework/` knows nothing
about any particular label.

## Three runtimes, one prompt library

Inference happens three ways, and all three render the same templates:

| Runtime | Credentials | How |
| --- | --- | --- |
| **agent** | none | `forge infer --mode agent` renders; the agent in your editor acts |
| **api** | your own key, from the environment | `forge infer --mode api` |
| **notebook** | none | `forge bundle export` writes sources for NotebookLM |

If each runtime carried its own copy of the wording they would drift, and the
same brief would produce different songs depending on where it ran. The template
is the artefact; the runtime is only delivery.

The notebook rendering is the clearest demonstration: the same `generate-song`
template produces a ~17,000-character API prompt with the dossier substituted
in, and a ~4,700-character notebook prompt that says *"See 03-dossier.md in this
notebook's sources."*

## The data model

`label/bands/<slug>/tracks.yaml` is the spine. One entry per song, carrying:

- **identity** — id, title, slug, band, era
- **assets** — audio and artwork paths plus their `sha256`
- **brief** — matrix suite, rhetorical stance
- **suno** — style prompt, declared BPM and key, song id and url
- **measurement** — `measured_bpm`, the full `analysis` block
- **glitch_log** — adjudicated anomalies with verified timecodes
- **lifecycle** — current stage and append-only history
- **provenance** — spark id, brief, prompt template and version, model

### Declared and measured are kept apart

`declared_bpm` and `measured_bpm` are separate fields, always. A measurement and
a declaration are different claims, and merging them destroys the only evidence
that they disagree — which they do on nine of twenty-one tracks in the reference
catalogue.

### Assets are fingerprinted

Every master and cover carries a `sha256`. The ledger stores measurements derived
from those files, so without a hash the numbers degrade silently: re-export a
different render of the same title and every timecode stays put while the thing
it describes changes underneath. `forge reconcile` reports drift.

## Why the ledger is data and not prose

The predecessor of this system kept its metadata ledger inside notebook
documents, as prose. Prose ledgers cannot be checked. An audit run against one
reported `PASS` for four files, three of which did not exist — the model had no
way to distinguish verifying a file from describing one.

Everything checkable is therefore checked in Python, and only genuine judgement
is delegated to a model. That division runs through the whole tool:

| Computed | Delegated |
| --- | --- |
| burned phrase reused | is the stance held for the whole song |
| bare or overloaded cue | is the narrator on-model |
| suite anchor missing | does a line contradict the substrate |
| tempo above measured ceiling | is the addressee specific enough |
| n-gram shared with another act | is it any good |

## The gates

- `reconcile` — audio, artwork, lyrics and ledger agree; hashes match; YAML parses;
  naming convention holds. Era- and stage-aware, so work in progress is reported
  without failing the build.
- `variety` — distribution of stance, suite, tempo, key and style prompt. The
  predecessor audit had six gates and all six measured *format*, which is
  trivially satisfiable; it passed a catalogue where four tracks shared a BPM, a
  key and a byte-identical sonic blueprint.
- `mine` — phrases a band has spent, and phrases crossing between acts.
- `prompt lint` — every slot used is declared and every slot declared is used.
"""

CONCEPTS = """\
# Concepts

## Suites and stances — two axes, not one

A **suite** is what a song is about. A **stance** is how it is spoken. They are
independent, and conflating them is the mistake this system exists to correct.

A lyrical matrix constrains vocabulary. It does not constrain syntax, and syntax
is where sameness lives. In the reference catalogue one act had four thematic
suites and six songs, and all six were the same speech act: second-person
accusation. The topic rotated; the posture never did. Another opened three
separate bridges on *"A deep lack of ___"* — not a vocabulary problem, and no
lexicon check would ever have caught it.

Eleven stances against four or five suites gives forty-plus distinct premises per
act instead of four, and the stance is what changes the sentences rather than
just the nouns.

## The narrator dossier

Each act fixes **who speaks, from where, at what hour, to whom, what they want,
and what they cannot admit.**

A fixed speaker generates consistent diction automatically, because word choice
follows from position. It does more for voice consistency than any word list.

Acts are differentiated by **room, hour and addressee** — concrete and checkable
— rather than by adjectives. In the reference roster four of five acts are alone;
the one with a crowd in the room is the only one that can be patient, and that
falls out of the room rather than being asserted.

The *cannot admit* field turns out to hold the most valuable unwritten material on
a roster: the only things the speaker is actually hiding.

## The shared substrate

When a roster is several facets of one person rather than several characters,
consistency stops depending on remembering invented lore and starts depending on
one set of real facts read several ways. Far more robust — and it lets one event
be written several times without repetition, which is the strongest format the
format offers.

## Register — aiming the glitch

Each act carries a **measured** breakage profile: the tempo ceiling and the
lexical shapes that break that particular voice, with the evidence.

This converts the Glitch Axiom from post-hoc rationalisation into an instrument.
If you know where a voice breaks, a hard word becomes *placeable*: put the
polysyllable where a slur reads as emphasis, and never on a word the line depends
on. In the reference catalogue one track lost the word *faders* to a slur and the
line lost its meaning with it; another lost *analog*, the word its own song was
named after. Both were placement decisions nobody made.

Where a register says **unmeasured**, it is genuinely unknown. Guessing a ceiling
and presenting it as known is the failure the measurement layer exists to end.

## The Glitch Axiom

Synthesis failures are kept, named under the act's own protocol, and left in the
mix. Punk did not overcome the limitations of cheap four-track recording; it made
them the sound.

Two consequences the tool enforces:

- The analyser finds candidates. **It never decides.** Which failures are badges
  of honour is a human judgement, and automating it would gut the idea.
- A glitch log is written *after* a render, never before. One written in advance
  is fabricated evidence.

## Eras

A label whose axiom is *leave the glitch in* does not sanitise its own back
catalogue. Tracks written before the standards existed are tagged
`era: pre-standard` and exempted from the matrix, stance and lexicon gates. They
still get lyric sheets and glitch logs. Their repetitions are not a compliance
failure — they are the corpus the burned lists are mined from.

## Sparks and provenance

The **spark** is the rawest human input: the argument you actually had, the phrase
you cannot place. `label/sparks/` is gitignored, because git is permanent and a
repo may go public. The committed brief references the spark by id and copies
nothing from it — a "derived summary" would leak it back in through the side door.

Provenance records which prompt template and version, which model, and which mode
produced each draft. The point is not bookkeeping: it means *"why is this song
like this?"* has an answer.

## Informed elicitation

Every human gate asks for exactly what it needs, informed by what the tool
already knows. The difference is between a form and a collaborator:

> **Form:** What do you want to write about?
>
> **Informed:** This act is 3-for-3 on accusation and has never used procedure.
> Suite B is its core suite and its least mined. Measured tempo 152–185 with no
> failures, so there is headroom the D-beat act does not have.

Both are questions. Only one is worth answering.
"""

GETTING_STARTED = """\
# Getting started

## Choose a tier

**No backend.** Take `bundles/fresh-spark/`, upload the files to one NotebookLM
notebook, and follow `00-START-HERE.md`. You need a vision and, ideally, a demo
song. Nothing else — no install, no command line.

**With the toolchain.** Everything below.

## Install

```bash
python3 -m venv .venv
./.venv/bin/pip install -e .                # core, and provides the `forge` command
./.venv/bin/pip install -e '.[analysis]'    # adds the audio-analysis extras
```

Python **3.12 or newer**. `forge docs` reads argparse internals to generate the
command reference and those attribute names are not public API.

Every command below is written as `forge`. That command exists only after the
editable install above — without it, use `python3 -m framework.forge` instead.
The two are the same entry point.

`ffmpeg` and `ffprobe` must be on `PATH` — the audio and artwork pipelines both
use them. Core commands run on stdlib plus `pyyaml`; only `forge analyze` needs
the extras.

## Orient yourself

```bash
python3 -m framework.forge status     # where every track sits
python3 -m framework.forge next       # what to do, and why
python3 -m framework.forge stages     # the process itself
```

Those three exist because an agent — or you, returning after a month — arrives
with no idea what the project needs.

## Start a label

Edit `label/label.yaml`: the label name, its axiom, and one entry per act with an
id prefix. Write `label/substrate.md` if the acts share a biography.

Then derive an act from a vision:

```bash
python3 -m framework.forge infer --id derive-band \\
  --vision "a dub soundsystem crew who only play at dawn, obsessed with tide tables"
```

Save the result as `label/bands/<slug>/band.yaml` and `dossier.md`.

## Write a song

```bash
# 1. capture the raw thing
forge spark --band <slug> --file note.md

# 2. read the proposed brief, change what you disagree with, then
forge spark --confirm --band <slug> --track <track-slug>

# 3. generate
forge infer --id generate-song --band <slug> --track <track-slug> --write

# 4. review — mechanical checks computed, judgement delegated
forge review --band <slug> --track <track-slug>
forge review --band <slug> --track <track-slug> --prompt

# 5. compile the sheet, take it to your generator, then bring the render back
forge ingest-audio --band <slug> --track <track-slug> --file "Take 3.mp3"

# 6. measure it
./.venv/bin/python -m framework.forge analyze --band <slug> --track <track-slug> --write

# 7. judge the failures — this one is yours alone
forge adjudicate --band <slug> --write
forge adjudicate --band <slug> --apply
```

## Import an existing catalogue

```bash
forge bootstrap                                   # seed ledgers from audio on disk
forge import-lyrics --band <slug> --source <harvest-doc>   # dry run first
forge artwork --write
forge fingerprint --write
forge reconcile
```

`bootstrap` and `import-lyrics` are both idempotent, and `import-lyrics` dry-runs
by default so you can check the parse before it writes anything.
"""


def build_framework() -> DocSet:
    ds = DocSet(kind="framework")
    ds.files = [
        DocFile("README.md", _framework_index()),
        DocFile("architecture.md", ARCHITECTURE),
        DocFile("concepts.md", CONCEPTS),
        DocFile("getting-started.md", GETTING_STARTED),
        DocFile("lifecycle.md", _lifecycle_doc()),
        DocFile("commands.md", _command_reference()),
    ]
    return ds


def _framework_index() -> str:
    return """\
# Documentation

| Document | What it covers |
| --- | --- |
| [Getting started](getting-started.md) | Install, first act, first song, importing a catalogue |
| [Concepts](concepts.md) | Suites and stances, dossiers, register, the Glitch Axiom, eras, provenance |
| [Architecture](architecture.md) | The framework/label split, three runtimes, the data model, the gates |
| [Lifecycle](lifecycle.md) | The nine stages and what each gate asks for |
| [Commands](commands.md) | Full command reference |
| `AGENTS.md` (repo root) | Rules for an agent working here — also emitted as `CLAUDE.md`, `.github/copilot-instructions.md` and `.kiro/steering/` |
| [Adversarial audit brief](adversarial-audit.md) | A reusable brief for an independent security, code and docs review. Any fork should run it. |
| [Audit report](audit-report.md) | Historical: the 2026-08-20 review, all findings since addressed. Kept for its method and calibration. |

`lifecycle.md` and `commands.md` are generated from the source. Regenerate after
any change:

```bash
python3 -m framework.forge docs framework
python3 -m framework.forge docs agents
```

The agent files are four copies of one source. They are duplicated because most tools inject their instructions directly rather than following a pointer — and generated, because four hand-maintained copies would drift.
"""


# ---------------------------------------------------------------------------
# catalog docs
# ---------------------------------------------------------------------------
def asset_link(out_root: Path, subdir: str, target: Path) -> str:
    """Link from a generated page to a committed asset.

    Depth is counted from the repository root to the page's own directory, not
    from the subdirectory name — getting that wrong made every artwork link one
    level short. And if the output root is outside the repo (a wiki clone, say),
    no relative path can reach the assets at all, so fall back to an absolute
    file URL and let `docs` report the caveat rather than emitting links that
    quietly 404.
    """
    try:
        page_dir = (out_root / subdir).resolve().relative_to(config_mod.REPO_ROOT)
    except ValueError:
        return target.resolve().as_uri()
    depth = len(page_dir.parts)
    return "../" * depth + target.relative_to(config_mod.REPO_ROOT).as_posix()


def assets_reachable(out_root: Path) -> bool:
    try:
        out_root.resolve().relative_to(config_mod.REPO_ROOT)
        return True
    except ValueError:
        return False


def _track_stats(t: dict) -> list[str]:
    a = t.get("analysis") or {}
    rhythm, tonal, asr, dsp = (
        a.get("rhythm") or {}, a.get("tonal") or {}, a.get("asr") or {}, a.get("dsp") or {}
    )
    bits: list[str] = []
    declared = ledger_mod.get_nested(t, "suno.declared_bpm")
    measured = t.get("measured_bpm")
    if declared and measured:
        agree = "" if rhythm.get("tempo_locked") else "  ⚠ disagree"
        bits.append(f"**Tempo** {measured:.0f} BPM measured / {declared} declared{agree}")
    elif measured:
        bits.append(f"**Tempo** {measured:.0f} BPM measured")
    elif declared:
        bits.append(f"**Tempo** {declared} BPM declared")
    if t.get("duration_s"):
        m, s = divmod(int(t["duration_s"]), 60)
        bits.append(f"**Length** {m}:{s:02d}")
    if asr.get("word_accuracy") is not None:
        verdict = asr.get("verdict", "")
        flag = "" if verdict == "ok" else f"  ⚠ {verdict}"
        bits.append(f"**Sheet match** {asr['word_accuracy']:.0%}{flag}")
    if dsp.get("peak_dbfs") is not None:
        bits.append(f"**Peak** {dsp['peak_dbfs']} dBFS")
    return bits


def _catalog_band(cfg: Config, slug: str, out_root: Path) -> str:
    spec = context_mod.band_spec(cfg, slug)
    bblock = spec.get("band") or {}
    sonic = spec.get("sonic") or {}
    all_rows = ledger_mod.load_band_tracks(cfg.bands[slug])

    # Releases and work in progress are counted separately everywhere below. A
    # brief has no title, no audio and no artwork, so rendering it beside finished
    # songs made the page look broken and inflated every figure on it.
    tracks: list[dict] = []
    in_progress: list[dict] = []
    for t in all_rows:
        target = tracks if lc_mod.is_released(lc_mod.assess(t).stage) else in_progress
        target.append(t)

    album = None
    album_dir = cfg.artwork_root / "albums" / slug
    if album_dir.exists():
        arts = sorted(album_dir.glob("*"))
        album = arts[0] if arts else None

    L: list[str] = [f"# {bblock.get('name', slug)}", ""]
    if album:
        L += [f"![{slug}]({asset_link(out_root, "catalog", album)})", ""]
    if bblock.get("role"):
        L.append(f"**{bblock['role']}**")
        L.append("")
    if bblock.get("disagreement"):
        L += [f"> {bblock['disagreement']}", ""]
    if bblock.get("facet_note"):
        L += [str(bblock["facet_note"]).strip(), ""]

    L += ["## Sound", ""]
    for key, label in (
        ("genre", "Genre"), ("style_prompt", "Style prompt"),
        ("bpm_nominal", "Nominal tempo"), ("vocal", "Vocal"),
    ):
        if sonic.get(key):
            L.append(f"- **{label}** — {str(sonic[key]).strip()}")
    gp = spec.get("glitch_protocol") or {}
    if gp.get("name"):
        L.append(f"- **Glitch protocol** — {gp['name']}: {str(gp.get('reading','')).strip()}")
    L.append("")

    # --- stats -------------------------------------------------------------
    stances = Counter(
        ledger_mod.get_nested(t, "matrix.stance") for t in tracks
        if ledger_mod.get_nested(t, "matrix.stance")
    )
    measured = [t["measured_bpm"] for t in tracks if t.get("measured_bpm")]
    L += ["## By the numbers", "", "| | |", "| --- | --- |"]
    L.append(f"| Releases | {len(tracks)} |")
    if in_progress:
        L.append(f"| In progress | {len(in_progress)} |")
    if measured:
        L.append(f"| Measured tempo range | {min(measured):.0f}–{max(measured):.0f} BPM |")
    reg = spec.get("register") or {}
    L.append(f"| Tempo ceiling | {reg.get('tempo_ceiling') or 'unmeasured'} |")
    if stances:
        L.append(f"| Stances used | {', '.join(f'{k} ×{v}' for k, v in stances.most_common())} |")
    total_glitches = sum(len(t.get("glitch_log") or []) for t in tracks)
    L.append(f"| Logged glitches | {total_glitches} |")
    L.append("")

    # --- matrix ------------------------------------------------------------
    if spec.get("suites"):
        L += ["## The matrix", ""]
        for sid, s in spec["suites"].items():
            used = sum(
                1 for t in tracks if ledger_mod.get_nested(t, "matrix.suite") == sid
            )
            L.append(f"### Suite {sid} — {s.get('name','')}  *({used} track{'s' if used != 1 else ''})*")
            L.append("")
            if s.get("tension"):
                L += [str(s["tension"]).strip(), ""]
            if s.get("juxtaposition"):
                L += [f"*Image:* {str(s['juxtaposition']).strip()}", ""]
            if s.get("anchors"):
                L += [f"*Anchors:* {', '.join(s['anchors'])}", ""]

    # --- tracks ------------------------------------------------------------
    L += ["## Releases", ""]
    for t in tracks:
        tslug = t.get("slug")
        L.append(f"### {t.get('title')}")
        L.append("")
        art = t.get("artwork")
        if art and (cfg.artwork_root / art).exists():
            L.append(f'<img src="{asset_link(out_root, "catalog", cfg.artwork_root / art)}" width="320" alt="{t.get("title")}">')
            L.append("")
        meta = [f"`{t.get('id')}`", f"era `{t.get('era')}`"]
        stage = lc_mod.assess(t).stage
        if stage:
            meta.append(f"stage `{stage}`")
        suite = ledger_mod.get_nested(t, "matrix.suite")
        stance = ledger_mod.get_nested(t, "matrix.stance")
        if suite:
            meta.append(f"suite {suite}")
        if stance:
            meta.append(f"stance {stance}")
        L += [" · ".join(meta), ""]

        url = ledger_mod.get_nested(t, "suno.url")
        if url:
            verified = ledger_mod.get_nested(t, "suno.url_verified")
            note = "" if verified else " *(link constructed from the song id, unverified)*"
            L += [f"[Listen on Suno]({url}){note}", ""]

        stats = _track_stats(t)
        if stats:
            L += ["  \n".join(stats), ""]

        sheet = t.get("lyric_sheet")
        if sheet and (config_mod.REPO_ROOT / sheet).exists():
            body = (config_mod.REPO_ROOT / sheet).read_text(encoding="utf-8")
            if "## Lyrics" in body:
                body = body.split("## Lyrics", 1)[1].strip()
            L += ["<details>", "<summary>Lyrics</summary>", "", "```", body, "```", "",
                  "</details>", ""]

        log = t.get("glitch_log") or []
        if log:
            L += ["<details>", f"<summary>Glitch log ({len(log)})</summary>", ""]
            for g in log:
                anchor = g.get("anchor") or {}
                where = anchor.get("timecode") or anchor.get("section") or "?"
                verified = "measured" if g.get("timecode_verified") else "by ear"
                L.append(f"- **{g.get('protocol')}** at {where} *({verified})* — "
                         f"{g.get('description','')}")
            L += ["", "</details>", ""]
        L.append("---")
        L.append("")

    # --- work in progress ---------------------------------------------------
    # Listed rather than hidden. Omitting it would let the catalogue imply the
    # ledger holds nothing else, which is the same kind of false completeness the
    # inflated count was. Kept separate and plainly labelled, with what each one is
    # actually waiting on, so it reads as a song being written and not as a gap.
    if in_progress:
        L += ["## In progress", "",
              "Not releases. These are in the pipeline and are excluded from every "
              "figure above.", ""]
        for t in in_progress:
            a = lc_mod.assess(t)
            bits = [f"`{t.get('id')}`", f"stage `{a.stage}`"]
            suite = ledger_mod.get_nested(t, "matrix.suite")
            stance = ledger_mod.get_nested(t, "matrix.stance")
            if suite:
                bits.append(f"suite {suite}")
            if stance:
                bits.append(f"stance {stance}")
            L.append(f"### {t.get('title')}")
            L += ["", " · ".join(bits), ""]
            if a.next_stage:
                who = "a human" if a.blocked_on_human else "the tool"
                L += [f"Next: **{a.next_stage}** — {who} advances it."
                      + (f" Waiting on `{'`, `'.join(a.missing)}`." if a.missing else ""),
                      ""]
            L += ["---", ""]
    return "\n".join(L)


def _catalog_index(cfg: Config, out_root: Path) -> str:
    label = context_mod.label_spec()
    lblock = label.get("label") or {}
    results, summary = variety_mod.run(cfg)

    # Releases and work in progress, split per band. Counting every ledger row as
    # a track put 22 on this page while certification checked 21 and the label
    # README said 21 — three numbers, none of them saying which it meant.
    all_tracks: dict[str, list[dict]] = {}
    wip_tracks: dict[str, list[dict]] = {}
    for slug, band in cfg.bands.items():
        rel, wip = [], []
        for t in ledger_mod.load_band_tracks(band):
            (rel if lc_mod.is_released(lc_mod.assess(t).stage) else wip).append(t)
        all_tracks[slug], wip_tracks[slug] = rel, wip

    total = sum(len(v) for v in all_tracks.values())
    total_wip = sum(len(v) for v in wip_tracks.values())
    runtime = sum(
        t.get("duration_s") or 0 for v in all_tracks.values() for t in v
    )

    L: list[str] = []
    # Banner above the heading, which is where a reader's eye starts. Declared in
    # label.yaml so `framework/` stays generic — a label's own artwork has no
    # business being a path inside the toolchain.
    hero = cfg.catalog_hero
    if hero:
        L += [
            f'<img src="{asset_link(out_root, "catalog", hero)}" '
            f'alt="{lblock.get("name", "")}" width="100%">',
            "",
        ]
    L += [f"# {lblock.get('name','Catalogue')}", ""]
    if lblock.get("tagline"):
        L += [f"*{lblock['tagline']}*", ""]
    if lblock.get("axiom"):
        L += [f"> {lblock['axiom']}", ""]

    L += ["## The roster", "", "| Act | Role | Position | Releases |", "| --- | --- | --- | --- |"]
    for slug in cfg.bands:
        spec = context_mod.band_spec(cfg, slug)
        b = spec.get("band") or {}
        count = str(len(all_tracks[slug]))
        if wip_tracks[slug]:
            count += f" *(+{len(wip_tracks[slug])} in progress)*"
        L.append(
            f"| [{b.get('name', slug)}]({slug}.md) | {b.get('role','')} | "
            f"{b.get('disagreement','')} | {count} |"
        )
    L.append("")

    L += ["## Totals", "", "| | |", "| --- | --- |"]
    L.append(f"| Acts | {len(cfg.bands)} |")
    L.append(f"| Releases | {total} |")
    if total_wip:
        L.append(f"| In progress | {total_wip} |")
    L.append(f"| Runtime | {runtime // 60} min |")
    dist = summary.get("label_stances") or {}
    if dist:
        L.append(f"| Stances used | {len(dist)} of {len(summary.get('known_stances') or [])} |")
    L.append("")

    unused = summary.get("unused_stances") or []
    if unused:
        L += [
            "## Never written",
            "",
            f"{len(unused)} of the eleven stances have never been used on this "
            f"roster: {', '.join(f'`{u}`' for u in unused)}.",
            "",
            "Each is an available song.",
            "",
        ]

    canonical = label.get("canonical_phrases") or []
    if canonical:
        L += [
            "## Phrases allowed to cross acts",
            "",
            "Everything else shared between two acts is the roster collapsing into "
            "one voice. These are deliberate:",
            "",
        ]
        L += [f'- "{p}"' for p in canonical]
        L.append("")

    L += [
        "---",
        "",
        "Generated from the ledger by `forge docs catalog`. Every figure here is "
        "computed, not maintained by hand.",
        "",
        "A playable version with inline audio is at `index.html` — GitHub strips "
        "`<audio>` from markdown, so the player only works in the HTML build.",
    ]
    return "\n".join(L)


def _catalog_html(cfg: Config, out_root: Path) -> str:
    """A single playable page. The masters are in the repo, so the player needs no
    third party and no hosting plan — open it from the filesystem."""
    label = (context_mod.label_spec().get("label") or {})
    parts = [
        "<!doctype html><meta charset=utf-8>",
        f"<title>{html.escape(label.get('name','Catalogue'))}</title>",
        "<style>",
        "body{font:16px/1.55 system-ui,sans-serif;max-width:52rem;margin:2rem auto;"
        "padding:0 1rem;background:#111;color:#eee}",
        "h1{border-bottom:2px solid #444;padding-bottom:.3rem}",
        "h2{margin-top:2.5rem;color:#fff}",
        ".track{display:flex;gap:1rem;margin:1.5rem 0;padding:1rem;background:#1b1b1b;"
        "border-radius:8px;align-items:flex-start}",
        ".track img{width:140px;height:140px;object-fit:cover;border-radius:4px;flex:none}",
        ".meta{color:#999;font-size:.85rem;margin:.25rem 0}",
        "audio{width:100%;margin-top:.6rem}",
        "a{color:#8bd}",
        # The banner is a printed artefact on a bone-white ground and this page is
        # near-black, so it reads as a lit panel rather than a header bleeding into
        # the background. Left deliberately full-width and unfaded.
        ".hero{display:block;width:100%;height:auto;border-radius:6px;margin:0 0 1.5rem}",
        # Work in progress is deliberately not styled as a track: no cover slot, no
        # player, recessed and rule-marked. A brief rendered as a .track looked like
        # a release whose audio had failed to load.
        ".wip{margin:1.5rem 0;padding:.7rem 1rem;background:#161616;"
        "border-left:3px solid #444;border-radius:4px;color:#8a8a8a;font-size:.9rem}",
        "</style>",
    ]
    # Same image as the markdown index: the player is the catalogue's playable
    # build, not a second catalogue, so it should not have a second identity. Same
    # abstain rule too — no banner declared, or declared and absent, means no tag.
    hero = cfg.catalog_hero
    if hero:
        parts.append(
            f'<img class=hero src="{asset_link(out_root, "catalog", hero)}" '
            f'alt="{html.escape(label.get("name", ""))}">'
        )
    parts.append(f"<h1>{html.escape(label.get('name','Catalogue'))}</h1>")
    if label.get("axiom"):
        parts.append(f"<p><em>{html.escape(label['axiom'])}</em></p>")
    parts.append(
        "<p class=meta>Audio plays from the committed masters. No third party, "
        "no hosting — this file works from disk.</p>"
    )

    for slug in cfg.bands:
        spec = context_mod.band_spec(cfg, slug)
        b = spec.get("band") or {}
        parts.append(f"<h2>{html.escape(b.get('name', slug))}</h2>")
        if b.get("disagreement"):
            parts.append(f"<p><em>{html.escape(b['disagreement'])}</em></p>")
        rows = ledger_mod.load_band_tracks(cfg.bands[slug])
        released, wip = [], []
        for t in rows:
            (released if lc_mod.is_released(lc_mod.assess(t).stage) else wip).append(t)
        for t in released:
            art = t.get("artwork")
            audio = t.get("audio")
            parts.append("<div class=track>")
            if art and (cfg.artwork_root / art).exists():
                parts.append(
                    f'<img src="{asset_link(out_root, "catalog", cfg.artwork_root / art)}" alt="">'
                )
            parts.append("<div style=flex:1>")
            parts.append(f"<strong>{html.escape(str(t.get('title')))}</strong>")
            bits = [t.get("id"), f"era {t.get('era')}"]
            if t.get("measured_bpm"):
                bits.append(f"{t['measured_bpm']:.0f} BPM measured")
            parts.append(f"<div class=meta>{html.escape(' · '.join(map(str, bits)))}</div>")
            url = ledger_mod.get_nested(t, "suno.url")
            if url:
                parts.append(f'<div class=meta><a href="{html.escape(url)}">Suno</a></div>')
            if audio and (cfg.audio_root / audio).exists():
                parts.append(
                    f'<audio controls preload=none '
                    f'src="{asset_link(out_root, "catalog", cfg.audio_root / audio)}"></audio>'
                )
            else:
                # Now reachable only for a RELEASED track whose master is missing,
                # which certification reports as a gap. Before the split it fired
                # on every brief, so the one case that means something was buried
                # among cases that meant nothing.
                parts.append("<div class=meta>no master on disk</div>")
            parts.append("</div></div>")

        for t in wip:
            a = lc_mod.assess(t)
            bits = [str(t.get("id")), f"stage {a.stage}"]
            if a.next_stage:
                bits.append(
                    f"next: {a.next_stage}"
                    f" ({'human' if a.blocked_on_human else 'tool'})"
                )
            parts.append(
                "<div class=wip><strong>"
                f"{html.escape(str(t.get('title')))}</strong><br>"
                f"In progress — {html.escape(' · '.join(bits))}</div>"
            )
    return "\n".join(parts) + "\n"


def build_catalog(cfg: Config, out_root: Path) -> DocSet:
    ds = DocSet(kind="catalog")
    ds.files.append(DocFile("catalog/README.md", _catalog_index(cfg, out_root)))
    for slug in cfg.bands:
        ds.files.append(DocFile(f"catalog/{slug}.md", _catalog_band(cfg, slug, out_root)))
    ds.files.append(DocFile("catalog/index.html", _catalog_html(cfg, out_root)))
    if not assets_reachable(out_root):
        ds.files.append(DocFile("catalog/ASSETS-NOTE.md", ASSETS_NOTE))
    return ds


ASSETS_NOTE = """# Asset links in this build

This catalogue was generated outside the repository, so artwork and audio cannot
be reached by a relative path. Links fall back to absolute `file://` URLs, which
work on the machine that generated them and nowhere else.

If these pages are going somewhere other people will read — a wiki, a static
host — the assets need to travel with them, or the links need rewriting to
wherever the images and masters actually live.
"""


def format_result(result: dict) -> str:
    lines = ["=" * 78, f"DOCS  {result['kind']}", "=" * 78]
    lines.append(f"root: {result['root']}")
    lines.append(f"{result['count']} files")
    lines.append("")
    for f in result["files"]:
        lines.append(f"   {f}")
    return "\n".join(lines)
